# Generated by Django 4.1.7 on 2023-02-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
