# Generated by Django 4.1.7 on 2023-02-23 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gbill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gbill.person'),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gbill.person'),
        ),
    ]
