# Generated by Django 4.1.7 on 2023-02-23 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbill', '0002_item_is_deleted_alter_bill_amount_alter_bill_desc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name']},
        ),
    ]
